### PR TITLE
Use new EPOXY_CORE_PATH override to select ESP8266 core provided by this project

### PR DESCRIPTION
**Pull request by bxparks**
In https://github.com/bxparks/EpoxyDuino/pull/29, I added the ability for an end-user to specify a different Arduino core than the one supplied by EpoxyDuino. The variable `EPOXY_CORE_PATH` in a Makefile overrides the default.

I updated the Core files in EspMock to become self-contained. I removed and changed a bunch of unnecessary files. Then I updated `tests/network-tests/Makefile` to point the Core files hosted in this project, like this:

```make
APP_NAME := network-tests
ARDUINO_LIBS := AUnit TinyMqtt EspMock ESP8266WiFi
ARDUINO_LIB_DIRS := ../../libraries
EPOXY_CORE_PATH := ../../cores/esp8266
include ../../../EpoxyDuino/EpoxyDuino.mk
```

Seems to work.

I will provide more details in https://github.com/bxparks/EpoxyDuino/discussions/27.

### CODE REVIEW

**Comment by hsaturn** [comment]
Note: Auto checks have failed.

At first (and very fast) glance, I think that this PR make a hudge duplicates code.

Arduino.cpp: same file
avr_stdlib.cpp: same file
avr_stdlib.h: same file
IPAddress.cpp: same file
IPAddress.h: same file
main.cpp: same file
pgmspace.h: same file
Printable.h: same file
Print.cpp: same file
Print.h: same file
StdioSerial.cpp: same file
StdioSerial.h: same file
Stream.cpp: same file
Stream.h: same file
WCharacter.h: same file
WString.cpp: same file
WString.h: same file

I think that using at max at possible the same source is better.
Main differences in fact are pins definition and some interrupts or ADC things.
Lot of things are common for all platforms, especially for just a Mock.

I'll take time tomorrow to study more longer this PR.

Thanks Brian

**Comment by bxparks** [comment]
The tests will pass after bxparks/EpoxyDuino#29 is submitted.

**Comment by hsaturn** [comment]
> 
> 
> The tests will pass after [bxparks/EpoxyDuino#29](https://github.com/bxparks/EpoxyDuino/pull/29) is submitted.

Yes, sorry, I was going to remove this note when I realized that EPOXY_CORE_PATH was not greped in EpoxyDuino :-)

**Comment by hsaturn** [comment]
Maybe we could modify that way

1/ EpoxyDuino/cores/epoxy   -> Should be generic and thus used by any kind of Mock (EspMock for example)

2/ EpoxyDuino/cores/Arduino.h -> Should be moved in let say EpoxyDuino/hardware/arduino
3/ EspMock/cores/esp8266/Arduino.h -> Should be moved in let say EspMock/hardware/esp8266

then allow to choose the correct hardware ?

Thus Mocks (yet EspMock) will still benefit of enhancement from EpoxyDuino mocks by removing code duplicates.

Do you think this is a good idea ?

See you tomorrow :-)
_____________________________________________
( In fact, I would even move EspMock/hardware/esp8266 in EpoxyDuino/hardware/esp8266 and let EpoxyDuino manages the hardware => EspMock is adding some specific libraries such as ESPAsyncTCP ) but this is another topic.

**Comment by hsaturn** [comment]
I have to read carefully your mail before going further.

See you tomorrow Brian :-D

**Comment by hsaturn** [comment]
Hi Brian, still waiting for the [#29](https://github.com/bxparks/EpoxyDuino/pull/29) to be merged. Test are still in failure yet.

**Comment by bxparks** [comment]
Everything is submitted. I have updated the README.md with the latest instructions. Take a look at the changes I made to your `tests/network-tests/Makefile`. I added the `EPOXY_CORE_PATH` variable. And `EspMock` is no longer required in `ARDUINO_LIBS`. If you add additional mock libraries, keep adding them to the `EspMock/libraries/` directory.

**Comment by hsaturn** [comment]
Great !

I have ported my [TinyMqtt library ](https://github.com/hsaturn/TinyMqtt) to Esp32 and was waiting for all these changes in order to be able to write some Aunit tests for the Esp32.

Thanks Brian

**Pull request merged**
